name: Test and Publish
on: [ push ]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container: adoptopenjdk/openjdk11:jdk-11.0.11_9-centos
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: mitre-tdp/github-ci-scripts
          token: '${{ secrets.READ_CI_SCRIPTS }}'
          path: scripts/ci
      - run: ${GITHUB_WORKSPACE}/scripts/ci/ci-install-certs.sh
      - run: ${GITHUB_WORKSPACE}/scripts/ci/ci-testUnit.sh "${{ github.ref }}" "${{ secrets.CODEV_NAME_IDAASS_USERS }}" "${{ secrets.CODEV_TOKEN_IDAASS_USERS }}"
      - uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          check_name: unit-test-report
          report_paths: '**/test-results/**/*.xml'
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: unit-test-artifact
          path: '**/build/reports/tests/**/*'
  publish-snapshots:
    runs-on: ubuntu-latest
    needs: [ unit-tests ]
    if: success() && github.ref == 'refs/heads/main'
    container: adoptopenjdk/openjdk11:jdk-11.0.11_9-centos
    steps:
      # Install git before checkout so that the checkout action can use it to clone the repo and log us in (note centos ships with an older version - so update it)
      - run: |
          yum -y install http://opensource.wandisco.com/centos/7/git/x86_64/wandisco-git-release-7-2.noarch.rpm
          yum install git -y
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: mitre-tdp/github-ci-scripts
          token: '${{ secrets.READ_CI_SCRIPTS }}'
          path: scripts/ci
      - run: ${GITHUB_WORKSPACE}/scripts/ci/ci-install-certs.sh
      - run: ${GITHUB_WORKSPACE}/scripts/ci/ci-publish-snapshot.sh "${{ secrets.CODEV_NAME_IDAASS_DEVELOPERS }}" "${{ secrets.CODEV_TOKEN_IDAASS_DEVELOPERS }}"